<?php
//Get years
$yStart=$_POST["yStart"];
$yEnd=$_POST["yEnd"];
//Declarations utilizes years
include('../declarations.php');
?>
<html>
<head>
<title>Stochastic Draws</title>
<link rel="stylesheet" type="text/css" href="help.css" />
</head>

<body>

<center><h1>The Stochastic Process</h1></center>
The stochastic Baseline is generated by FAPRI after the deterministic Basline is completed. The process of generating stochastic projects involves producing distributions 
around certain  variables and simulating the models 500 hundred times resulting in stochastic draws. As sampling all possible sources of uncertainty is not feasible, a sufficient
number of factors that impact both supply and demand uncertainty are drawn so that the resulting price and quantity distributions are acceptably consistent with historical observations.
<br/><br/>
<center><h1>Stochastic Variables</h1></center>
The stochastic variables come from five basic areas - crop yields, exogenous energy 
and cost variables, domestic demand, domestic stockholding and, as noted above, 
reduced form equations for the rest of the world represented through trade 
equations. The segmentation into these groupings is largely a matter of 
practicality, where utilising problematic spurious correlations may be worse than 
assuming no direct correlation of the error terms. 
<br/><br/>
<center><h1>Generating 500 Draws</h1></center>
In practice the generation of these stochastic draws is a combination of art and 
science. In order to generate the 500 draws, some persistence is imposed through a lagged 
dependant variable, with an empirical distribution applied to multiplicative 
adjustment terms. There is a restriction on how much oil prices can move within a 
particular year, but over time the oil price can climb to high (or fall to low) levels. 
Based on the estimated distributions, 500 correlated random draws are made of 
the selected variables. The FAPRI-Missouri stochastic modelling system is solved 
for each of the 500 sets of exogenous variables and generates the values of the 
endogenous variables. The models are simulated using SAS and Excel, with 
stochastic draws generated using Simitar

<p>&nbsp;
<img align="right" src="logo.png" alt="FAPRI logo">
<p><input type="button" value="Close" onClick="javascript:window.close();" />

</body>
</html>